### ISSUE TITLE
App-Lovin Max Banner Resolution Issue after closing the interstitial ad.

### ISSUE THREAD

**Issue by goharjaved** [AppLovin/AppLovin-MAX-Unity-Plugin#362] opened 2024-04-16 19:43 UTC
### MAX Plugin Version

6.4.3

### Unity Version

2021.3.35

### Device/Platform Info

IOS 17.3

### Current Behavior

I am facing applovin banner placement issue on IOS. When we close the interstitial ad the banner jump to the centre of the screen. I have tried all the solutions but unable to fix this issue. It looks that IOS screen canvas snap to some pixels down.

### How to Reproduce

-Install the Demo App
-Show Banner Ad
- Show interstitial ad after completion banner will move to the centre of the screen.

### Additional Info

https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/79394070/8d0058ee-6245-4a9a-bd3c-d84f6f7cb1af

**Comment by santoshbagadi** [comment] 2024-04-16 19:48
Hi @goharjaved , this is a known issue and we are working on a fix for this. If you wish to test the fix for us right now, you can do so by replacing [this](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/604c28373f4f272aeab3142143770fdb2d89f2a9/DemoApp/Assets/MaxSdk/AppLovin/Plugins/iOS/MAUnityAdManager.m#L1710) line in `Assets/MaxSdk/AppLovin/Plugins/iOS/MAUnityAdManager.m` file to the following

```
UILayoutGuide *layoutGuide = superview.window ? superview.window.safeAreaLayoutGuide : superview.safeAreaLayoutGuide;
```

**Comment by goharjaved** [comment] 2024-04-17 06:24
Hi @santoshbagadi , after replacing banner is not showing only black bar is showing.

**Comment by goharjaved** [comment] 2024-04-17 06:28
Hi @santoshbagadi , thanks for the solution.

**Comment by santoshbagadi** [comment] 2024-04-25 16:12
@YeonjoonJung we are working on more robust fix that would fix the issue for our ads. We'll update here once we have the fix released.

**Comment by maximilianbuck** [comment] 2024-05-07 00:14
Hi @YeonjoonJung 
In version 6.4.4 of our Unity plugin we added a potential fix. It's behind a setting though so you have to enable it like this:
`MaxSdk.SetExtraParameter("pisw", "true");`

**Comment by soqman** [comment] 2024-05-07 10:39
i tryed to use MaxSdk.SetExtraParameter("pisw", "true");

it doesn't help

**Comment by maximilianbuck** [comment] 2024-05-07 20:52
@soqman could you please share a device log of as session where you reproduce the issue with [our verbose logging enabled](https://developers.applovin.com/en/unity/overview/advanced-settings/#enable-verbose-logging)?

**Comment by soqman** [comment] 2024-05-08 07:47
[srd_bugreport_2024-05-08T06_57_51.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/15245524/srd_bugreport_2024-05-08T06_57_51.txt)

**Comment by maximilianbuck** [comment] 2024-05-08 17:56
@soqman that looks to be a Unity log, sorry if it wasn't clear but I'm looking for the native device log, ie from Console or Xcode. Could you share that as well?

**Comment by soqman** [comment] 2024-05-09 12:19
[Uploading Console.txt…]()

**Comment by soqman** [comment] 2024-05-09 12:20
[Console.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/15262167/Console.txt)

**Comment by maximilianbuck** [comment] 2024-05-09 18:37
@soqman we found an issue with the fix and will have to make an update to our SDK. I will circle back when that gets released.
Just fyi that log that doesn't have any information from our native logging, if I had to guess our SDKs verbose logging is not enabled.

**Comment by soqman** [comment] 2024-05-09 19:35
I don't have xcode handy and have had some difficulties. I apologize for that. I'm pretty sure Verbose Logging is enabled in the config file. However, I have not called it through xcode. If there is a difference, it would be worth clarifying what the checkbox is for. I would appreciate any suggestions on how to avoid this bug in the current version.

**Comment by maximilianbuck** [comment] 2024-05-14 15:35
Unfortunately there is no local way to get around this at this time. We'll need the next SDK release to address the issue.

**Comment by alexwonton** [comment] 2024-05-21 07:46
I am facing the same issue with version 6.5.2. 
It seems like I cannot even press the cross button to close the ads. 

May I know if there is any update on this topic? 

![IMG_8961](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/100409697/3221d835-9d46-453d-8fca-da37a940f489)

**Comment by maximilianbuck** [comment] 2024-05-21 14:51
@alexwonton I assume you're using the extra parameter? The bug with ads not being closeable should've been fixed with Unity Plugin 6.5.0. 
I just tried reproducing any issue with version 6.5.2 of our Plugin in our demo app but wasn't able to see any issue. I was able to close all the ads without issues and the safe area (and thus banner and UI position) was not affected.
Could you try to reproduce this with our demo app and share the project with us if it does?
If it doesn't reproduce could you share a device log with [our verbose logging enabled](https://developers.applovin.com/en/unity/overview/advanced-settings/#enable-verbose-logging)?

**Comment by alexwonton** [comment] 2024-05-21 22:41
@maximilianbuck, thanks for your quick response. 
I think you are right. After I remove everything and reload the package, the issue is now gone. 
Thank you very much anyway :)

**Comment by khambadkone** [comment] 2024-07-09 03:34
We mediate AppLovin through LevelPlay (IronSource) and are facing this problem.
<img width="1068" alt="Screenshot 2024-07-09 at 9 01 36 AM" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/2083666/ab2f7862-a015-4041-81e7-19d4c9f74e4e">

We use Level Play mediation (v8.0.0) and have updated to the Applovin UnityAdapter 4.3.50.0.
Added the following  line before initialising IronSource
MaxSdk.SetExtraParameter("pisw","true"); 

But we still face this issue.

1. Why does this problem happen ?
2. Is there a fix for users who mediate the AppLovin SDK?

**Comment by dkasenko** [comment] 2024-07-11 12:04
Same

**Comment by maximilianbuck** [comment] 2024-08-02 09:18
Hi @fmoyano,
Have you tried enabling the setting by calling `MaxSdk.SetExtraParameter("pisw", "true");`?

**Comment by fmoyano** [comment] 2024-08-02 09:23
> Hi @fmoyano, Have you tried enabling the setting by calling `MaxSdk.SetExtraParameter("pisw", "true");`?

Not really. From the messages above I assumed this didn't work. I mean these messages:


> i tryed to use MaxSdk.SetExtraParameter("pisw", "true");
> 
> it doesn't help

And after that, you said this:

> @soqman we found an issue with the fix and will have to make an update to our SDK. I will circle back when that gets released. Just fyi that log that doesn't have any information from our native logging, if I had to guess our SDKs verbose logging is not enabled.

... and this:

> Unfortunately there is no local way to get around this at this time. We'll need the next SDK release to address the issue.

So from all this I assumed it was clear this didn't help, but maybe I misunderstood?

**Comment by maximilianbuck** [comment] 2024-08-02 09:27
@fmoyano The relevant SDK release was 6.5.0 so it should work on 6.6.1

**Comment by fmoyano** [comment] 2024-08-02 10:00
> @fmoyano The relevant SDK release was 6.5.0 so it should work on 6.6.1

Ok, got it, thanks. So should I call this before MaxSdk.InitializeSdk() or once the sdk has been initialized?

**Comment by maximilianbuck** [comment] 2024-08-02 10:04
It just needs to be set before you show the ad. So after initialization is fine.

**Comment by mkud** [comment] 2024-09-20 06:28
Can you tell me the mechanism of action of this setting?

Why didn't you make it enabled by default? Are there any side effects?

**Comment by maximilianbuck** [comment] 2024-09-20 14:03
@mkud It presents the Store page in a separate window which does have the side effect of showing it in portrait regardless of device orientation.

**Closed by maximilianbuck** 2024-09-20 14:03 UTC
Labels: bug

**Comment by Lorenzo45** [comment] 2024-10-03 21:09
@fmoyano @mkud can you confirm the issue is resolved after calling `MaxSdk.SetExtraParameter("pisw", "true");` on plugin version 6.5.0+?

**Comment by fmoyano** [comment] 2024-10-04 10:33
> @fmoyano @mkud can you confirm the issue is resolved after calling `MaxSdk.SetExtraParameter("pisw", "true");` on plugin version 6.5.0+?

Yes, using that call fixed the issue for us.
