### ISSUE TITLE
Android Ad Review Not Building

### ISSUE THREAD

**Issue by joshua-matchala** [AppLovin/AppLovin-MAX-Unity-Plugin#218] opened 2022-12-20 00:28 UTC
When building with the latest unity sdk (5.6.1) and having MAX ad review enabled and set correctly with the SDK key:

This error keeps coming up when building to android:

**Error [AppLovin MAX] Failed to add AppLovin Quality Service plugin. Quality Service Plugin Added?: False, Quality Service Repo added?: False, Quality Service dependency added?: False**
UnityEngine.Debug:LogError (object)
MaxSdkLogger:UserError (string) (at Assets/MaxSdk/Scripts/MaxSdkLogger.cs:55)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:GenerateUpdatedBuildFileLines (System.Collections.Generic.List`1<string>,string,bool) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:415)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:AddQualityServiceBuildScriptLines (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:115)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinPostProcessGradleProject:OnPostGenerateGradleAndroidProject (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessAndroidGradle.cs:28)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

There is no custom launcher templates or gradle templates.

Tried everything I can think of to fix, but no luck. Need advice.

Thanks

**Comment by santoshbagadi** [comment] 2022-12-20 14:46
Closing as duplicate of: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/206.

@joshua-matchala as requested in the other ticket, could you please share the exported project's `build.gradle` files and if you are using any custom gradle templates?

**Closed by santoshbagadi** 2022-12-20 14:46 UTC
