### ISSUE TITLE
Ios Crash on start watching Ad

### ISSUE THREAD

**Issue by ztranger** [AppLovin/AppLovin-MAX-Unity-Plugin#352] opened 2024-04-05 15:04 UTC
### MAX Plugin Version

6.4.1

### Unity Version

2021.3.26f1

### Device/Platform Info

Ios platform 

### Current Behavior

When start to watch Ad ios device crashed

checked on iPhone6, iPhoneXR, iPad Pro, iPhone 12
os versions 17.4.1, 16.3.1, 12.5.5

Crashed: com.apple.root.default-qos
0  UnityFramework                 0x26d93f4 il2cpp::vm::Thread::GetThreadStaticData(int) + 492 (il2cpp-object-internals.h:492)
1  UnityFramework                 0x5492ec8 selector_thread(void*) (.cold.1) + 656 (threadpool-ms-io.cpp:656)
2  UnityFramework                 0x5484c74 selector_thread(void*) (.cold.1) + 656 (threadpool-ms-io.cpp:656)
3  UnityFramework                 0x5484de4 selector_thread(void*) (.cold.1) + 656 (threadpool-ms-io.cpp:656)
4  UnityFramework                 0x50d7218 selector_thread(void*) (.cold.1) + 656 (threadpool-ms-io.cpp:656)
5  UnityFramework                 0x300b458 selector_thread(void*) (.cold.1) + 656 (threadpool-ms-io.cpp:656)
6  UnityFramework                 0x26ed5f8 il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) + 578 (Runtime.cpp:578)
7  UnityFramework                 0x26ed458 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 572 (Runtime.cpp:572)
8  UnityFramework                 0x1c01238 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) + 292 (ScriptingApi_Il2Cpp.cpp:292)
9  UnityFramework                 0x1c0cfd4 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 298 (ScriptingInvocation.cpp:298)
10 UnityFramework                 0x1c1d7dc MonoBehaviour::HandleNotifications(void*, int, MessageData&) + 60 (ScriptingNativeTypes.h:60)
11 UnityFramework                 0x1a52284 GameObject::SendMessageAny(MessageIdentifier const&, MessageData&) + 1319 (GameObject.cpp:1319)
12 UnityFramework                 0x1b20c48 SendMessageToEveryone(MessageIdentifier const&, MessageData) + 1498 (GameObjectUtility.cpp:1498)
13 UnityFramework                 0x2141fd8 UnityPause + 398 (LibEntryPoint.mm:398)
14 UnityFramework                 0x46aae0 __33-[MAUnityAdManager didDisplayAd:]_block_invoke + 822 (MAUnityAdManager.m:822)
15 libdispatch.dylib              0x5fa38 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x607d4 _dispatch_client_callout + 16
17 libdispatch.dylib              0x4c80 _dispatch_queue_override_invoke + 684
18 libdispatch.dylib              0x11030 _dispatch_root_queue_drain + 372
19 libdispatch.dylib              0x118d4 _dispatch_worker_thread2 + 128
20 libsystem_pthread.dylib        0xc1b4 _pthread_wqthread + 464
21 libsystem_pthread.dylib        0xecd4 start_wqthread + 4

### How to Reproduce

Call function 
MaxSdk.ShowRewardedAd

actualy I saw this fix in the last version of SDK
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/294

and this was about allocations in event forwarding. Could be related, because we have crash on SendMessage call and get NRE here

### Additional Info

[crash_session_c102452aefae406da0a20c25b6edc21c_DNE_1_v2_stacktrace.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/14886669/crash_session_c102452aefae406da0a20c25b6edc21c_DNE_1_v2_stacktrace.txt)

**Comment by alkanyunus** [comment] 2024-04-05 16:11
+ same here

**Comment by santoshbagadi** [comment] 2024-04-05 18:27
Thank you for raising the issue. We've found the cause of the issue and are working on a fix. We'll update here once the fix is live.

**Comment by santoshbagadi** [comment] 2024-04-06 01:08
We've released a fix for this in the latest version of our plugin ([6.4.2](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_6_4_2))

**Closed by santoshbagadi** 2024-04-06 01:08 UTC
Labels: bug
