### ISSUE TITLE
Crash on app launch: com.applovin.adview.AppLovinFullscreenActivity.onDestroy

### ISSUE THREAD

**Issue by urmobi-tokman** [AppLovin/AppLovin-MAX-Unity-Plugin#372] opened 2024-05-08 09:02 UTC
### MAX Plugin Version

6.4.4

### Unity Version

2022.3.18f1

### Device/Platform Info

Android 11-14

### Current Behavior

App crashes on launch (from Firebase : 93% of crash events for this issue happened in the first 5 seconds of a user's session).

### Expected Behavior

App does not crash.

### How to Reproduce

We are not able to reproduce it, observe the issue in crashlytics. This bug appeared after updating to version 6.4.4 from 6.4.3

### Additional Info

[games.urmobi.found.it_issue_37a36fccb501d520aaafd9ccb3280897_crash_session_663AF55F009B0001096724BD2DE202A3_DNE_0_v2_stacktrace.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/15246390/games.urmobi.found.it_issue_37a36fccb501d520aaafd9ccb3280897_crash_session_663AF55F009B0001096724BD2DE202A3_DNE_0_v2_stacktrace.txt)

**Comment by santoshbagadi** [comment] 2024-05-08 12:28
Hi @urmobi-tokman , thank you for raising the issue. We are already working on a fix for this issue and will include it in the next SDK release.

**Comment by leeyonglan** [comment] 2024-05-12 00:44
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5714)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5754)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:47)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2415)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:211)
  at android.os.Looper.loop (Looper.java:300)
  at android.app.ActivityThread.main (ActivityThread.java:8410)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:559)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:954)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.applovin.impl.sdk.k.a(com.applovin.impl.oj)' on a null object reference
  at com.applovin.adview.AppLovinFullscreenActivity.onDestroy (SourceFile:1)
  at android.app.Activity.performDestroy (Activity.java:8838)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1475)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5701)

the same error

**Comment by p0w1nd** [comment] 2024-05-14 04:53
I'm also facing this issue in my Unity game projects.

**Comment by soqman** [comment] 2024-05-14 07:06
me too

**Comment by xtixi** [comment] 2024-05-14 07:52
me2 😞

**Comment by duyuit** [comment] 2024-05-14 13:44
I have the same problem, it is really affecting my revenue, please fix it soon

**Comment by thinhletan1995** [comment] 2024-05-14 13:49
Me too, hope it will be fixed soon

**Comment by alkanyunus** [comment] 2024-05-14 13:58
It's still the same here.

**Comment by soqman** [comment] 2024-05-15 08:07
hi @santoshbagadi  is it included to 4.5.0 ?

**Closed** 2024-05-15 08:33 UTC
Labels: bug

**Comment by shefich** [comment] 2024-05-16 11:02
AppLovin Unity Mediation Plugin Changelog
 [Version 7.2.2]
The issue exist!

**Comment by shefich** [comment] 2024-05-16 11:02
From here: https://developers.google.com/admob/unity/mediation/applovin#applovin-unity-mediation-plugin-changelog

**Comment by santoshbagadi** [comment] 2024-05-16 16:55
@shefich that adapter is published by AdMob. You would have to reach out to AdMob directly requesting them to release a new adapter built against our SDK version 12.5.0.

**Comment by Holdsgggg** [comment] 2025-04-08 15:38
> [!WARNING]
>
