### ISSUE TITLE
Unity 6 Preview build error

### ISSUE THREAD

**Issue by hunght85** [AppLovin/AppLovin-MAX-Unity-Plugin#389] opened 2024-06-03 03:49 UTC
### MAX Plugin Version

6.5.2

### Unity Version

Unity 6000.0.1

### Device/Platform Info

Android 14

### Current Behavior

Error android build

### How to Reproduce

[SafeDK-ERROR] Android variants not detected.
Please make sure you place the directive:
apply plugin: 'applovin'
after you apply the Android plugin in your build.gradle file

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Volumes/MyData/Unity/Projects/Galaxiga/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
> Could not find method packaging() for arguments [build_79b3ak34n16texbfiq0ccfzhs$_run_closure2$_closure4@6c79c288] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':launcher'.
> Failed to notify project evaluation listener.
   > compileSdkVersion is not specified. Please add it to build.gradle
   > Android variants not detected.
     Please make sure you place the directive:
     apply plugin: 'applovin'
     after you apply the Android plugin in your build.gradle file

**Comment by santoshbagadi** [comment] 2024-06-03 16:55
@hunght85 , we're going to release a new version of our plugin that will fix this issue. In the mean time do you mind trying the workaround mentioned here: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/376#issuecomment-2121341734

Also, going to close this as duplicate.

**Comment by JonathanLiuApp** [comment] 2024-06-04 18:58
@hunght85 I was not able to reproduce your error in Unity 6 preview. Could you share the gradle files in your project? Could you also check if you are able to reproduce this in our demo app?

**Comment by hunght85** [comment] 2024-06-05 02:22
<img width="727" alt="Screenshot 2024-06-05 at 09 20 27" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/146641235/315d92bb-de2a-45fc-9f9c-9b06010c7747">


apply plugin: 'com.android.library'
apply plugin: 'applovin'
**APPLY_PLUGINS**

dependencies {
    implementation "androidx.startup:startup-runtime:1.1.1"
    implementation "androidx.fragment:fragment:1.6.2"
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.applovin.mediation:google-adapter:[23.0.0.1]' // Assets/MaxSdk/Mediation/Google/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:unityads-adapter:4.10.0.0' // Assets/MaxSdk/Mediation/UnityAds/Editor/Dependencies.xml:4
    implementation 'com.applovin:applovin-sdk:12.4.2' // Assets/MaxSdk/AppLovin/Editor/Dependencies.xml:4
    implementation 'com.google.android.ump:user-messaging-platform:2.1.0' // Assets/MaxSdk/AppLovin/Editor/Dependencies.xml:5
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packaging {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/armeabi-v7a/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    ndkPath "**NDKPATH**"

    compileSdk **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdk **MINSDK**
        targetSdk **TARGETSDK**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lint {
        abortOnError false
    }

    androidResources {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**

**Comment by hunght85** [comment] 2024-06-05 08:26
![Uploading Screenshot 2024-06-05 at 15.13.13.png…]()

**Comment by JonathanLiuApp** [comment] 2024-06-06 20:39
Could you check that you have `Custom Main Gradle Template`, `Custom Base Gradle Template`, and `Custom Gradle Properties Template` enabled in your project settings? If not, could you enable them, resolve dependencies using the External Dependency Manager, and try to build again?

**Comment by hunght85** [comment] 2024-06-06 21:06
<img width="493" alt="Screenshot 2024-06-07 at 03 57 31" src="https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/146641235/4a9bccf4-894e-4f44-992b-cf53b997233b">
I had all of them and try resolve dependencies using the External Dependency Manage but nothing changed.

**Comment by santoshbagadi** [comment] 2024-06-07 22:17
Was this app updated from an older version of Unity? If so, the gradle templates might be old and you may have to re-generate them by disabling and re-enabling the templates.

**Closed** 2024-06-12 16:21 UTC
Labels: bug, duplicate

**Comment by huy24112001** [comment] 2024-07-12 16:21
i have a same problem . What files do I need to delete?

**Comment by hunght85** [comment] 2024-07-13 08:50
> i have a same problem . What files do I need to delete? @hunght85
Bạn xóa hết file trong Asset -> Plugin -> Android. . rồi tick lại trong player setting

**Comment by mayo-tds** [comment] 2025-04-23 14:17
> > i have a same problem . What files do I need to delete? [@hunght85](https://github.com/hunght85)
> > Bạn xóa hết file trong Asset -> Plugin -> Android. . rồi tick lại trong player setting

ie:
You delete all files in Asset -> Plugin -> Android. . then tick again in player setting
