### ISSUE TITLE
ATT should not display, if the user does not consent anything on GDPR form

### ISSUE THREAD

**Issue by bartutiryakioglu** [AppLovin/AppLovin-MAX-Unity-Plugin#325] opened 2024-01-08 12:05 UTC
### Feature Description

We are rejected because of UMP & ATT with the following reasons

Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed your app includes a GDPR prompt and an App Tracking Transparency permission request, but they are implemented in a way that might confuse the user. 

Specifically, your app shows the App Tracking Transparency permission request after the user has already requested you not to track on the GDPR prompt. 

In addition to App Tracking Transparency, it is important to include all disclosures required by local laws and regulations wherever your app is distributed. These disclosures should be implemented in a way that is clear and respects the user's choices, regardless of the order in which they are presented to the user. 

Next Steps

If the user denies permission to track once, do not ask them to allow tracking again within the same permission request flow. There should be no tracking activity until the user grants permission to track.

If your app shows the GDPR prompt before showing the App Tracking Transparency permission request, there is no need to modify the wording of the GDPR prompt.

When I looked through google forums [https://groups.google.com/g/google-admob-ads-sdk/c/huUa7eyMTEE](url), they said that the ATT popup not showing if the user does not consent anything from the GDPR form. Can you do the same thing for Applovin SDK it's urgent. This problem blocks us to release new versions of our game.

**Comment by bartutiryakioglu** [comment] 2024-01-08 16:41
[AppLovinSdk] DEBUG [ALGoogleCMPAdapter] Consent form finished showing
[AppLovinSdk] DEBUG [ALSdk] Transitioning to state: [ALConsentFlowStateEvent: id=13, type=event, isInitialState=0, name=gdpr_ok]
[AppLovinSdk] DEBUG [ALSdk] Transitioning to state: [ALConsentFlowState: id=1001, type=decision, isInitialState=0]
[AppLovinSdk] DEBUG [ALSdk] Transitioning to state: [ALConsentFlowState: id=14, type=att, isInitialState=0]
[AppLovinSdk] DEBUG [ALEventService] Tracking event: "gdpr_ok"

I can see that AppLovin is openning att popup even if I did not give consent on CMP Form

**Comment by agrobost** [comment] 2024-01-17 10:09
We have exactly the same problem. I tried to activate "idfa explainer" in admob and it doesn't work, the ATT is always requested even when the player doesn't give consent.

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/14184466/d94ca607-37dc-443b-a047-c4062bcad1e8)

Here is a response template for the iOS validation team if anyone is interested:
"Dear Apple App Review Team,

We sincerely appreciate your detailed review and the issues you've highlighted regarding the GDPR prompt and the App Tracking Transparency (ATT) request. We understand the importance of clear and respectful consent management for our users.

We have promptly reached out to Applovin, the provider of the advertising mediation SDK we use, to rectify the identified issues as per your guidelines. We are working closely with their team to ensure that the consent management process (TCFv2 + ATT) aligns seamlessly with Apple's requirements, and we expect a swift resolution.

We kindly request your consideration to allow our application's current version on the App Store. This version not only includes other critical bug fixes that enhance user experience and app stability but also represents a commitment to user privacy and data protection. We assure you that the consent management update will be implemented as soon as possible.

Thank you for your understanding and support in this matter.

Best regards"

**Comment by MathieuHpGerwin** [comment] 2024-01-29 09:42
Hello!
Any update about it? Do you have a release date in mind? Is it already scheduled or being tested?
Is it about days, weeks or months?
I'm scheduling our next update on it
Thx

**Comment by wootaejeon** [comment] 2024-01-29 20:09
Hi @MathieuHpGerwin, the fix will be included in our next sdk release which is currently planned for mid February. We'll let you know once it goes live.

**Comment by Kvinster** [comment] 2024-02-02 11:22
@wootaejeon , am I correct to understand that "IDFA explainer message" won't appear in any case until the next sdk release? We have enabled it in Admob dashboard, but still not seeing it in build. Is it intended behavior atm or does it warrant a separate issue?

**Comment by santoshbagadi** [comment] 2024-02-02 17:52
@Kvinster we do not support the `IDFA explainer message` from AdMob's flow. Our flow only supports the CMP prompt. You'd need to integrate Google's UMP directly if you wish to use the IDFA explainer.

**Comment by wootaejeon** [comment] 2024-02-20 04:44
@bartutiryakioglu @agrobost @MathieuHpGerwin The fix is now live with our SDK version 12.2.0 (Unity plugin v6.2.0) - our Terms and Privacy Policy Flow will no longer show the ATT request when user denies permission to track on GDPR prompt.

**Closed by wootaejeon** 2024-02-20 04:44 UTC
Labels: enhancement

**Comment by chuongdp** [comment] 2024-12-30 09:23
Hi @wootaejeon, I've met this issue with the latest MaxSDK as my attached image below
Do you have any updates on this one?
<img width="541" alt="Screenshot 2024-12-30 at 16 19 53" src="https://github.com/user-attachments/assets/8a7f64aa-59a6-4916-bd21-9368035b8d01" />
![Screenshot 2024-12-30 at 16 20 30](https://github.com/user-attachments/assets/7a32b0b1-c01b-4ad5-987c-7d8d9a23fc0b)
![Screenshot 2024-12-30 at 16 21 19](https://github.com/user-attachments/assets/9344f974-fdfb-4ca9-92f4-6bbeddd05296)
