### ISSUE TITLE
Max mediator's plugin for Unity doesn't seem to be compatible with multi threading calls

### ISSUE THREAD

**Issue by FGavinhos** [AppLovin/AppLovin-MAX-Unity-Plugin#40] opened 2020-07-03 22:13 UTC
I made a test which consisted in running your sample project (setting it up according to the instructions in this repository's README file) in a device and following these steps:

1. Open the app while the device is connected to the internet;
2. Put the device in offline mode after it finished loading the ads;
3. Watch ads of the same type until you consumed all the cached ones;
4. Notice that the status label is showing some "failed to connect" error message;
5. Reconnect the device to the web;
6. Notice that the app recovered well and downloaded new ads that you can normally watch again;

I ran the same test in a build with only one change: the method that loads ads was turned into a C#'s async function and set to await 500 milisseconds before doing its stuff, which makes it to run asynchronously. And during the step 5, the app crashed.

Then I made a third test in which I forced this task to run in the Unity's Main Thread and it worked well once again. My guess is that there is something in your sdk that directly depends on something from Unity's runtime resources, so it crashes when running in a parallel thread.

It would be great if your solution had support for being called within async operations, but in case you already knew that this was happening and it's meant to be this way, I think that it would be usefull to warn about it in the documentation, specially in the README's getting started session. Just because it causes a bug that's critical and very hard to find out what's happening.

**Comment by thomasmso** [comment] 2020-07-04 02:39
@FGavinhos - Thanks for reporting the issue - before we dive in, do you mind sharing a code snippet for when you got the app to crash, and the crash report as well? Thanks.

**Comment by FGavinhos** [comment] 2020-07-06 16:58
@thomasmso Sure! Sorry for not doing so in the first message.

Code:

`    private async void LoadInterstitial()
    {
        await Task.Delay(500);
        await LoadInterstitialTask();
    }

    private async Task LoadInterstitialTask()
    {
        interstitialStatusText.text = "Loading...";

        await Task.Delay(500);

        MaxSdk.LoadInterstitial(InterstitialAdUnitId);
    }`

**Comment by FGavinhos** [comment] 2020-07-06 17:59
@thomasmso Hello! Thanks for answering! Sure! I'm sending what you asked for. Sorry for not doing so in the first message.

**Code:**

In HomeScreen class, I replaced the `LoadInterstitial()` function for the following code:

```
private async void LoadInterstitial()
{
await Task.Delay(500);
await LoadInterstitialTask();
}

private async Task LoadInterstitialTask()
{
    interstitialStatusText.text = "Loading...";

    await Task.Delay(500);

    MaxSdk.LoadInterstitial(InterstitialAdUnitId);
}
```

About the logs, I spent this morning trying to reproduce de decribed flow in order to gather them, but I'm getting a 5001 error code during ads caching process. I'm in contact with your support to check what's going on. Once I manage to repeat the test, I'll send the logs in this thread.

**Comment by santoshbagadi** [comment] 2020-07-07 00:54
@FGavinhos , I was not able to reproduce the issue on both Android and iOS. Were you seeing the issue on Android or iOS or on both platforms. Also, what version of Unity IDE are you using. A screen shot of the [integration manager](https://dash.applovin.com/documentation/mediation/unity/mediation-adapters#integration-manager-(version-2.0.0-or-higher)) would help us to check if this is related to one of the mediated networks.

**Comment by FGavinhos** [comment] 2020-07-07 13:17
Hi @santoshbagadi. I saw this issue happening on Android. I haven't tested on iOS. I'm using Unity 2018.4.24f1. Here's the requested screenshot:
![image](https://user-images.githubusercontent.com/67807856/86785241-c7bd6080-c038-11ea-9a34-96b7a823334b.png)

I haven't open this screen for this project. I just ran the sample it comes from this repository. Could my problem be related to not having the network's sdks installed yet?

If so, my gues is that the issue I reported happens only when an exception is thrown by a network integration routine during an async call. Maybe some part of the solution is trying to reach Unity's console or crash handler and that's why it crashes when running out of the main thread.

**Comment by FGavinhos** [comment] 2020-07-07 22:47
Hi guys. I have some news about this case. I tryied the reverse test. I went back to my app that was crashing and replaced all the async flows around Max mediator's calls by synchronous callbacks structure. Then I set the network for my device's ads to be Unity Ads through the dashboard (in this project this network is properly integrated) and executed the steps I described in the first post. The result is that my app crashed, which got me some steps back in finding out the cause of the crashes. The good news are that I managed to capture the logs for this execution, so I'd like to share them with you. 

[log.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/4887473/log.txt)

I'm working on finding a new suspect for this case. It's certainly something with the ads because it's clearly affected by the network I set in the dashboard. For example, when I get ads from admob this crash never happens, but when they're from Unity Ads, it was consistently reproduced in three out of three tries.

**Comment by santoshbagadi** [comment] 2020-07-08 00:43
Thank you for all the information. This is helpful and I'll try to reproduce with Unity Ads.

**Comment by santoshbagadi** [comment] 2020-07-08 06:56
I was not able to reproduce the issue with Unity Ads either. It also seems like the crash happens while watching the ad itself

```
07-07 19:35:10.389: I/InputDispatcher(4062): Window 'Window{a93927c u0 br.com.tapps.myicecreamtruck/com.unity3d.player.UnityPlayerActivity}' spent 2418.4ms processing the last input event: MotionEvent
07-07 19:35:10.389: I/InputDispatcher(4062): Window 'Window{a93927c u0 br.com.tapps.myicecreamtruck/com.unity3d.player.UnityPlayerActivity}' spent 2332.8ms processing the last input event: MotionEvent
07-07 19:35:10.389: I/InputDispatcher(4062): Window 'Window{a93927c u0 br.com.tapps.myicecreamtruck/com.unity3d.player.UnityPlayerActivity}' spent 2324.2ms processing the last input event: MotionEvent
07-07 19:35:10.389: I/InputDispatcher(4062): Window 'Window{a93927c u0 br.com.tapps.myicecreamtruck/com.unity3d.player.UnityPlayerActivity}' spent 2315.7ms processing the last input event: MotionEvent
07-07 19:35:10.389: I/InputDispatcher(4062): Window 'Window{a93927c u0 br.com.tapps.myicecreamtruck/com.unity3d.player.UnityPlayerActivity}' spent 2307.5ms processing the last input event: MotionEvent
07-07 19:35:10.389: I/InputDispatcher(4062): Window 'Window{a93927c u0 br.com.tapps.myicecreamtruck/com.unity3d.player.UnityPlayerActivity}' spent 2300.9ms processing the last input event: MotionEvent
07-07 19:35:10.390: E/MessageQueue-JNI(6113): java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-07 19:35:10.390: E/MessageQueue-JNI(6113): Version '2019.3.15f1 (59ff3e03856d)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
```

And it also says that the Unity version used is 2019.2.15f1. Just wanted to double check that these logs are the same ones that are causing the crash since you mentioned that you were using Unity 2018.4.24f1.

Do you mind sending a screenshot of the integration manager for the project where the issue is being reproduced. Maybe I can try with all the networks that are installed in your project.

**Comment by FGavinhos** [comment] 2020-07-08 18:55
Oh, I'm sorry for the misunderstanding. The sample project I cloned from this repository is running on Unity 2018.4. My app, which was logging crashes in production and is the reason why I started studying the behaviour that brought me to this issue, is the one I used for the last test and is running on Unity 2019.2. The logs are from my own app's execution.

Also about it, I have news. I searched the call stack and found another async call that I missed during my first attempt to force the ads flow to be called synchronously. When I transformed this function into a synchronous callback, the app recovered well after the 5th step of the STR I decribed above, confirming my suspects that the crashes are related to calling Max' API out of the main thread.

This is how the integration manager is set for this project:
![image](https://user-images.githubusercontent.com/67807856/86958428-8c9f5800-c132-11ea-81f1-3bfbb94d4315.png)
![image](https://user-images.githubusercontent.com/67807856/86958477-9f199180-c132-11ea-9b2c-7653fc680ea2.png)
![image](https://user-images.githubusercontent.com/67807856/86958500-a8a2f980-c132-11ea-94cc-6de371d50fb6.png)

With this last test I'm pretty sure that it has something to do with the asynchronous call. Forcing it to run synchronously workarounded the problem for me, but I think it would be great if we manage to get to the root of this issue. Is there any other thing I can do to help with it?

**Comment by santoshbagadi** [comment] 2020-07-09 00:42
Unfortunately I was not able to reproduce the issue even with all the networks included. Were you able to reproduce the issue in this demo app, if so, could you share your version of the app. If not, could you share a debug apk of you app.

You can send the app to my email address: santosh.bagadi@applovin.com

**Comment by santoshbagadi** [comment] 2020-07-17 18:16
Resolved via email. Due to a limitation by Unity, calls to Android and iOS require to happen on Unity main thread. The solution is to call MAX APIs on the main thread.

We will add a note to our documentation.

**Closed by santoshbagadi** 2020-07-17 18:16 UTC

**Comment by FGavinhos** [comment] 2020-07-17 18:51
Thank you for all the support!

**Comment by pedro15** [comment] 2022-12-16 20:41
> Resolved via email. Due to a limitation by Unity, calls to Android and iOS require to happen on Unity main thread. The solution is to call MAX APIs on the main thread.
> 
> We will add a note to our documentation.

That shold be a feature to be honest. 

Running that kind of tasks in the main thread will only decrase the performance of the game while max-sdk in loading an Ad in the background, or firing an event, 

i'm experiencing performance issues related to max sdk when it fires an event, or it starts loading an Ad.

**Comment by santoshbagadi** [comment] 2022-12-16 21:34
Hi @pedro15 , unfortunately it is a limitation on Unity itself and we can't call into our native Android/iOS layers on the background thread. They would need to be called on the main thread. 

Our actual ad loading itself would happen on the background thread. So, there shouldn't be a lot of performance issues. 

Could you please share more details on what the specific issues you are seeing related to performance, so that we can investigate further?

**Comment by pedro15** [comment] 2022-12-16 22:52
> 

Sure, i'm experiencing "lag spikes" of performance when a MaxSDK event is fired:
![Image](https://i.imgur.com/GeGASpO.png)

MaxSDK Version:
5.6.1
Unity Version: 
2021.3.15f1

Platform: Android
Test Device: 
Samsung Galaxy A20 (Android 11)

( it seems to be generating huge Garbage Collection, and it seems to come from the MaxSDK )

**Comment by santoshbagadi** [comment] 2022-12-17 00:09
Thank you for the additional info. We'll investigate and notify here once we have any updates.

**Comment by pedro15** [comment] 2023-01-04 17:49
Any news?

**Comment by JonathanLiuApp** [comment] 2023-01-11 19:41
Hi @pedro15, we are currently investigating the issue. Would you be able to share a sample project where we can reproduce the issue?

**Comment by pedro15** [comment] 2023-01-12 16:27
> 

Sure, later i will give you a sample project, issue is happening in the project that i'm working on when an ad is loading OR it fires an ad

**Comment by Anti-Ded** [comment] 2024-04-30 16:01
Hello, Have same problem(
Error 1:
```
Error [AppLovin MAX] Caught exception in publisher event: OnRewardedAdRevenuePaidEvent, exception: UnityEngine.UnityException: TrySetSetString can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
  at UnityEngine.PlayerPrefs.SetString (System.String key, System.String value) [0x00000] in <00000000000000000000000000000000>:0
  at MaxSdkCallbacks.InvokeEvent[T1,T2] (System.Action`2[T1,T2] evt, T1 param1, T2 param2, System.String eventName, System.Boolean keepInBackground) [0x00000] in <00000000000000000000000000000000>:0
  at MaxSdkCallbacks.ForwardEvent (System.String eventPropsStr) [0x00000] in <00000000000000000000000000000000>:0
  at MaxSdkBase.HandleBackgroundCallback (System.String propsStr) [0x00000] in <00000000000000000000000000000000>:0
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
  at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) [0x00000] in <00000000000000000000000000000000>:0
MaxSdkCallbacks:InvokeEvent(Action`2, T1, T2, String, Boolean)
MaxSdkCallbacks:ForwardEvent(String)
MaxSdkBase:HandleBackgroundCallback(String)
UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
```
Error 2:
```
UnityException: TrySetSetString can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.PlayerPrefs.SetString (System.String key, System.String value) (at <00000000000000000000000000000000>:0)
MaxSdkCallbacks.InvokeEvent[T1,T2] (System.Action`2[T1,T2] evt, T1 param1, T2 param2, System.String eventName, System.Boolean keepInBackground) (at <00000000000000000000000000000000>:0)
MaxSdkCallbacks.ForwardEvent (System.String eventPropsStr) (at <00000000000000000000000000000000>:0)
MaxSdkBase.HandleBackgroundCallback (System.String propsStr) (at <00000000000000000000000000000000>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)
MaxSdkCallbacks:ForwardEvent(String)
MaxSdkBase:HandleBackgroundCallback(String)
UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
```
![2024 04 30 18 43 28](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/67957247/9ac6016a-2bff-422f-afba-190f37d5906a)
![2024 04 30 18 43 36](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/67957247/a5929a94-91a6-40bc-9cc0-5dd9ee152cfd)

using this script at Loading state

```
using System;
using UnityEngine;

public class AdHelper : MonoBehaviour
{
    [SerializeField] float secsBetweenRewards = 0;
    [SerializeField] bool rewardResetinterCD = true;
    [SerializeField] string rewardKey;
    [SerializeField] string maxsdkKey;
    public static AdHelper instance;
    Action<bool> onComplete;
    float rewardTime;
    
    private void Awake()
    {
        if (AdHelper.instance != null)
        {
            Destroy(gameObject);
            return;
        }
        DontDestroyOnLoad(this);
        instance = this;
        MaxSdk.SetSdkKey(maxsdkKey);
        MaxSdk.InitializeSdk();
        
        MaxSdkCallbacks.OnSdkInitializedEvent += (MaxSdkBase.SdkConfiguration sdkConfiguration) =>
        {
            MaxSdk.LoadRewardedAd(rewardKey);
        };

        Events();
    }


    public bool RewardAvailable()
    {
        bool result = MaxSdk.IsRewardedAdReady(rewardKey);

        if (result)
            result = Time.realtimeSinceStartup - rewardTime > secsBetweenRewards;
        return result;
    }
    public void Reward(string placement, Action<bool> onComplete)
    {
        if (RewardAvailable())
        {
            this.onComplete = onComplete;
            MaxSdk.ShowRewardedAd(rewardKey);  // error appears after this
        }
        else
            onComplete?.Invoke(false);
    }

    void Events()
    {
        MaxSdkCallbacks.Rewarded.OnAdReceivedRewardEvent += Rewarded_OnAdReceivedRewardEvent;
        MaxSdkCallbacks.Rewarded.OnAdDisplayFailedEvent += Rewarded_OnAdDisplayFailedEvent;
        MaxSdkCallbacks.Rewarded.OnAdHiddenEvent += Rewarded_OnAdHiddenEvent;
    }

    private void Rewarded_OnAdHiddenEvent(string arg1, MaxSdkBase.AdInfo arg2)
    {
        onComplete?.Invoke(false);
        MaxSdk.LoadRewardedAd(rewardKey);
    }

    private void Rewarded_OnAdDisplayFailedEvent(string arg1, MaxSdkBase.ErrorInfo arg2, MaxSdkBase.AdInfo arg3)
    {
        onComplete?.Invoke(false);
        MaxSdk.LoadRewardedAd(rewardKey);
    }

    private void Rewarded_OnAdReceivedRewardEvent(string arg1, MaxSdkBase.Reward arg2, MaxSdkBase.AdInfo arg3)
    {
        // error appears before this
        onComplete?.Invoke(true); // this invokes fine
        MaxSdk.LoadRewardedAd(rewardKey);
    }
}
```

from game scene using method Reward()
error apperas after string 48 and before 75
there is no async or ienumerators(
Please help!

**Comment by santoshbagadi** [comment] 2024-04-30 19:11
Hi @Anti-Ded , the `OnRewardedAdRevenuePaidEvent` callbacks events are sent on a background thread. If you need to Unity Engine APIs, you'd need to post them to the main thread to fix the crash. 

We are also working on a new feature that allows you to get all the callbacks on the main thread in an upcoming release.

**Comment by Anti-Ded** [comment] 2024-04-30 20:02
So, how can i track revenuesusing Adjust?

**Comment by rbyjoswald** [comment] 2025-05-27 07:28
> Hi [@Anti-Ded](https://github.com/Anti-Ded) , the `OnRewardedAdRevenuePaidEvent` callbacks events are sent on a background thread. If you need to Unity Engine APIs, you'd need to post them to the main thread to fix the crash.
> 
> We are also working on a new feature that allows you to get all the callbacks on the main thread in an upcoming release.

Was the feature ever implemented to receive callbacks on the main thread?
