### ISSUE TITLE
ViewTreeObserver.dispatchOnGlobalLayout crash on Android

### ISSUE THREAD

**Issue by abogarsukov-braingames** [AppLovin/AppLovin-MAX-Unity-Plugin#260] opened 2023-06-07 14:07 UTC
### MAX Plugin Version

5.10.0

### Unity Version

2021.3.26

### Device/Platform Info

Android

### Current Behavior

Application crashes after showing an ad. This usually happens when an app goes to background during an ad, and then it's activated in a few hours (via notification or manually). We're not sure if this is something caused by AppLovin, as there's not references to it in the stack traces. The indirect evidence is the crash happening after presenting an ad. Please see the crashlytics report attached.

### How to Reproduce

We're not able to reproduce the issue on our side.

### Additional Info

[com.wordfarm.scapes_issue_785bd376e4155f35067f0ba036a2cd1b_crash_session_64806362039600017B31EEF0B918D09A_DNE_0_v2_stacktrace.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/11677885/com.wordfarm.scapes_issue_785bd376e4155f35067f0ba036a2cd1b_crash_session_64806362039600017B31EEF0B918D09A_DNE_0_v2_stacktrace.txt)

**Comment by thomasmso** [comment] 2023-06-08 05:27
Thanks for reporting this issue @abogarsukov-braingames. How often is this crash occurring as a % of DAUs?

**Comment by abogarsukov-braingames** [comment] 2023-06-08 07:25
@thomasmso it's about 0.15% of DAU affected.

**Comment by wojciech-juszczynski** [comment] 2023-06-12 08:00
Same issue for us. In our case ~0.50% of DAU are affected.

**Comment by thomasmso** [comment] 2023-06-12 16:54
Thanks both - we're investigating.

**Comment by thomasmso** [comment] 2023-06-15 17:49
@wojciech-juszczynski - No updates on the origins of this crash (MAX SDK vs one of the mediated networks). Which SDKs and versions would you roll back to?

**Comment by wojciech-juszczynski** [comment] 2023-06-16 10:45
@thomasmso after checking our repos - our main lead is APS Android SDK, it looks like crash started when we updated mentioned SDK to 9.8.1, we will try to rollback it to 9.7.1 (our previous version) and see if crash still occurs

**Comment by thomasmso** [comment] 2023-06-16 17:41
@wojciech-juszczynski - Thanks for the heads up. We don't have access to their source so we've been investigating within our own code. Please keep us posted if the crash improves.

**Comment by urmobi-tokman** [comment] 2023-06-22 05:18
Hello @wojciech-juszczynski 
We facing this issue too.
It is impossible to say which particular mediator is causing this problem (facebook, aploving, google admob, amazon, liftoff and etc they were all in the logs after which the crash occurred)
65% of crash rate from Samsung devices (50% android 13)
Do you have any update on this issue? Have you already tried rolling back a version? Did it bring any results?

**Comment by alvarshahanji** [comment] 2023-06-30 20:38
@abogarsukov-braingames @wojciech-juszczynski @urmobi-tokman 
Wanted to update the thread here. The Amazon team shared that the issue is fixed in their latest APS SDK v9.8.3. The adapter is updated to certify the same. Thanks!

**Closed by alvarshahanji** 2023-06-30 20:38 UTC
Labels: bug
