### ISSUE TITLE
iOS Xcode build fails, missing symbols

### ISSUE THREAD

**Issue by edksen** [AppLovin/AppLovin-MAX-Unity-Plugin#252] opened 2023-05-04 15:42 UTC
### MAX Plugin Version

5.9.0

### Unity Version

2021.3.16f1

### Device/Platform Info

iOS

### Current Behavior

We have updated AppLovin Max Plugin for Unity in our project from 5.5.1 to 5.9.0 and start experience difficulties with iOS XCode build part.
It's missing symbols which is a part of Google-Mobile-Ads-SDK such as GADAdLoaderAdTypeCustomNative, GADAdLoaderAdTypeNative, etc. when archiving.

After Unity build with External dependency manager, we have this pod file (Due to company NDA compliances I left only AppLovin info visible):
![image](https://user-images.githubusercontent.com/72187607/236255270-0441a7ac-2280-4ec1-bffa-b4d4fc829fb0.png)

It includes AppLovinMediationGoogleAdapter, AppLovinMediationUnityAdsAdapter and AppLovinSDK (we are using Unity Ads and Google AdMob mediations in project)

On the top of that, pod install generates both Pods-Unity-Iphone and Pods-UnityFramework frameworks. Both has the same set of Target Dependencies. Except Pods-Unity-Iphone doesn't have Google-Mobile-Ads-SDK reference (Pods-UnityFramework has it).

After adding to pod file in Unity-Iphone section reference to AppLovinMediationGoogleAdapter, Xcode build doesn't have missing symbols errors.

### Expected Behavior

There are no problems with previous version of AppLovin plugin for Unity without extra workarounds in pod file. So I expect XCode build should works fine without such problems.

### How to Reproduce

Install AppLovin version 5.5.1 in Unity project, then update it to 5.9.0 and make iOS build (Unity+Xcode)

### Additional Info

Any help is greatly appreciated!

**Comment by alexboost222** [comment] 2023-05-04 15:47
+1 this is pretty annoying error.

**Comment by VladTempest** [comment] 2023-05-04 15:52
🚨 High-priority Bug 🚨  it has a major impact on our user experience. Your assistance in resolving this problem is greatly appreciated. We got similar problem with 5.9.0. 
Thank you in advance for your attention to this matter! 👍

**Comment by santoshbagadi** [comment] 2023-05-04 17:58
Hi All, I think the issue is due to adding the `Unity-iPhone` target. You should be able to fix this by opening the iOS Resolver Settings (**Assets > External Dependency Manager > iOS Resolver > Settings**) and unchecking **Add use_frameworks! to Podfile** and **Always add the main target to Podfile** as shown in the screenshot below.

![IMG_0047](https://user-images.githubusercontent.com/37196391/157342326-63dfabaa-55ee-41bd-977c-f62732dd4f4b.png)

**Comment by edksen** [comment] 2023-05-05 08:00
Hello @santoshbagadi!
Thanks for your help.
But unfortunately it doesn't help, because some of thirdparty frameworks are using swift pods, which could not be linked as static libraries. Pods installation fails with your suggestion about  iOS Resolver Settings.

**Comment by edksen** [comment] 2023-05-15 15:02
We get pod install error If use_frameworks option has been disabled
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/72187607/a7226c32-8e98-492f-a5f4-84e64c2e4e3f)
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/72187607/02b484f7-af70-483e-bba3-f9149e4630aa)

**Comment by santoshbagadi** [comment] 2023-05-15 19:31
Hi @edksen , thank you for all the info. For the Firebase issue, you can fix it by adding `use_modular_headers!` at the end of the `Podfile`.

To achieve this from Unity via post process scripts, you can use the following:

```
    public class PostProcessBuildIos
    {
        private const int BuildOrderPostGenPodfile = 41;
        private const string UseModularHeaders = "use_modular_headers!";

        [PostProcessBuild(BuildOrderPostGenPodfile)]
        public static void OnPostProcessBuild(BuildTarget target, string buildPath)
        {
            var podfilePath = Path.Combine(buildPath, "Podfile");

            // Check if the Podfile exists. If it doesn't, it could be that the CocoaPods for External Dependency Manager has bee disabled or External Dependency Manager has updated the build order constants.
            if (!File.Exists(podfilePath)) return;

            var lines = File.ReadAllLines(podfilePath).ToList();

            // Return if use_modular_headers! already exists.
            if (lines.Any(line => line.Contains(UseModularHeaders))) return;

            lines.Add("");
            lines.Add(UseModularHeaders);

            try
            {
                File.WriteAllText(podfilePath, string.Join("\n", lines.ToArray()) + "\n");
            }
            catch (Exception exception)
            {
                Debug.LogError("Failed to Add use_modular_headers! to PodFile. Podfile file write failed.");
                Console.WriteLine(exception);
            }
        }
    }
``` 

Please let me know if you have any questions.

**Comment by edksen** [comment] 2023-05-16 15:57
Hi @santoshbagadi!
Hope you are doing well!
Thank you for response. Unfortunately, our game crashes on start with this option.

`[general] Error loading /var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/UnityFramework.framework/UnityFramework (141):  dlopen(/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit

  Referenced from: <F5E25414-A386-3A4E-9DC1-CAAC5C5AAC28> /private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/UnityFramework.framework/UnityFramework

  Reason: tried: '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/System/Library/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file, not in dyld cache)

[general] Error loading /var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/UnityFramework.framework/UnityFramework (141):  dlopen(/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/FBAEMKit.framework/FBAEMKit

  Referenced from: <F5E25414-A386-3A4E-9DC1-CAAC5C5AAC28> /private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/UnityFramework.framework/UnityFramework

  Reason: tried: '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/private/var/containers/Bundle/Application/D011B79C-32EF-40DE-B711-A7D699E55779/MyName.app/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file), '/System/Library/Frameworks/FBAEMKit.framework/FBAEMKit' (no such file, not in dyld cache)
`

**Comment by santoshbagadi** [comment] 2023-06-13 20:31
Sorry for the late reply here, but you'd have to add the `FBAEMKit` framework to the embedded frameworks list to the main target to fix this startup crash.

**Comment by NudeNULL** [comment] 2023-10-04 13:54
We tried the script and it doesn't add automatically the line into the pod file(

**Comment by NudeNULL** [comment] 2023-10-04 15:38
Got the same issue here with FBAEMKit after using the script build post process, not sure what the answer means and how to do it, wonder if somebody got this fixed and automated the process for every build, for example like a post build script

**Comment by NudeNULL** [comment] 2023-10-05 18:54
So adding FBAEMKit via a post script did help to solve this specific crash reason, but there are anyway other errors that cause the crash anyway, did anybody solve this issue and have a crashless app start?

**Comment by santoshbagadi** [comment] 2024-04-12 16:47
We've updated our plugin (v6.4.3) to be able to work with the default EDM settings.

**Closed by santoshbagadi** 2024-04-12 16:47 UTC
Labels: bug
